theme: jekyll-theme-slate

scope:
  path: assets/img
  values:
      image: true
sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

title: "VGL Genome Portal" # the name of your site, e.g. ACME Corp.
tagline: "Track your VGP project at VGL"
email: "vgl@rockefeller.edu"
description: >- # this means to ignore newlines until "baseurl:"
author:
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
